Extend tests for admin controller
amplimindcc/backend pull request #127
Opened 2024-05-26 06:24 UTC by VincentFlemmig

Line coverage bei 94%
2 Tests schlagen noch fehl, da die implementierung im Controller noch fehlt

2024-05-26 10:10 UTC, SrNski requested changes
Paar tests failen noch

2024-05-26 16:15 UTC, VincentFlemmig commented on src/main/kotlin/de/amplimind/codingchallenge/controller/AuthController.kt
> +    @ApiResponse(responseCode = "409", description = "username or password is incorrect")
Der Endpoint wirft einen 409er error während der in der Doku und im Test ein 403 erwünscht ist. Wollte die Methoden nicht anpassen, also hab ich die Erwartungen angepasst

2024-05-26 16:15 UTC, VincentFlemmig commented on src/test/kotlin/de/amplimind/codingchallenge/controller/AuthControllerTest.kt
> +                status { isConflict() }
selbes wie oben

2024-05-30 15:01 UTC, Stefan7400 approved these changes

2024-05-30 15:01 UTC, merged