Endpoint and Logic for User Submission
amplimindcc/backend pull request #58
Opened 2024-04-20 20:38 UTC by VincInfo

2024-04-21 09:09 UTC, Stefan7400 requested changes

2024-04-21 09:23 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/service/SubmissionService.kt
> +            delay(3000)
Die delays sind einmal weil das code pushen erst passieren kann wenn das repo erstellt ist und der worklfow getriggert werden kann, wenn das yml file geuploaded ist. Ich habe es davor ja mit coroutines gemacht und mit async await, aber damit kommt github nicht klar irgendwie. Auch wenn ich mit await darauf warte, geht es nicht weil Gihub noch nicht ready ist irgendwie. Aber du hast vollkommen recht. Da kann man sich nochmal was ueberlegen. Vielleicht polling oder so.

2024-04-21 09:23 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/service/SubmissionService.kt
> +                delay(3000)
Selber Grund wie unten beschrieben.

2024-04-21 09:25 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/service/SubmissionService.kt
> +        runBlocking {
Nein, im Moment noch nicht, aber wuerde in einem Anderen Ticket nochmal das mit der parallelisierung machen. Dafuer ist das. Ich kann es vorerst aber auch raus machen wenn du willst.

2024-04-21 09:40 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/utils/ZipUtils.kt
> +            e.printStackTrace()
Jo hab ich da wohl vergessen, ergaenze ich gleich

2024-04-21 09:41 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/utils/ZipUtils.kt
> +            throw e
ergaenze ich auch noch

2024-04-22 15:04 UTC, Stefan7400 requested changes

2024-04-22 15:34 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/service/SubmissionService.kt
> +        val gitHubApiClient = createGitHubApiClient(accessToken)
Natuerlich nicht :D, wollte allgemein nur erstmal die grobe Logik implementieren, solche Sachen und auch zum Beispiel das Speichern des Github Access Tokens oder das Senden der Api Requests sind so Sachen, da haette ich halt Folgetickets gemacht. Aber klar, ich kann das auch noch in diesem Ticket machen. Bin ja dankbar fuer deine Reviews :D

2024-04-22 15:35 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/service/SubmissionService.kt
> +        if((submission.status == SubmissionStates.IN_IMPLEMENTATION).not()) {
ja, ich ueberleg auch mal was da am besten waere...

2024-04-22 15:45 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/service/SubmissionService.kt
> +        val gitHubApiClient = createGitHubApiClient(accessToken)
Und im Bezug auf Rollbacks bei Fehlern, das habe ich mir natuerlich auch schon gedacht. Dachte aber auch, das es besser waere, wenn wir dazu Tickets erstellen.

2024-04-22 15:58 UTC, VincInfo commented on src/main/kotlin/de/amplimind/codingchallenge/service/SubmissionService.kt
> +        if((submission.status == SubmissionStates.IN_IMPLEMENTATION).not()) {
Synchronized brauchen wir warscheinlich echt und ich finde das ist ein Grund mehr um zu versuchen die requests mit couroutines zu optimieren xD Nur ich hab das gemacht und Github kommt damit wie gesagt nciht klar. Es bekommt dann immer Conflicts, wenn ich files in gleiche unterorder pushe, warscheinlich wenn sich da die verschiednen Coroutines in die Quere kommen und folder erstellen wollen, die eigentlich schon von einer anderen Coroutine erstellt wruden oder so.

2024-04-28 11:21 UTC, Stefan7400 approved these changes

2024-04-28 11:22 UTC, merged