added optimistic locking
amplimindcc/backend pull request #61
Opened 2024-04-21 16:12 UTC by ris5266

resolves https://github.com/amplimindcc/backend/issues/51

2024-04-21 16:16 UTC, ris5266 commented
hab es jtzt mal mit optimistic locking implementiert kann es aber ggf. auch zu pessimistic locking ändern

2024-04-21 17:08 UTC, Stefan7400 commented
Da gibt es doch sicher noch weitere Entities bei denen man Optimistic Locking verwenden müsste, allein bei Project noch und dann bei den anderen auch? Sollte man dass hier nicht etwas später erst machen?

2024-04-21 17:12 UTC, Stefan7400 requested changes

2024-04-21 17:12 UTC, Stefan7400 commented on src/main/kotlin/de/amplimind/codingchallenge/service/UserService.kt
> +            throw IllegalStateException("The user was updated by another transaction")
There is a retry mechanism in spring boot (where we can define a retry amount how often a certain action should be redone until a exception is thrown

2024-04-21 19:06 UTC, ris5266 commented
> Da gibt es doch sicher noch weitere Entities bei denen man Optimistic Locking verwenden müsste, allein bei Project noch und dann bei den anderen auch? Sollte man dass hier nicht etwas später erst machen?

meinst du generell das ticket erst später machen? oder soll ichs bei den anderen entities doch noch hinzufügen?

2024-04-21 19:58 UTC, ris5266 commented
wo meintest du noch sollte mans hinzufügen? Habs in der ProjectService klasse jetzt noch geaddet aber ansonsten finde ich glaub ich auch nix mehr wos passen würde, aber ich kann mich auch täuschen

2024-04-22 07:42 UTC, Stefan7400 commented
> wo meintest du noch sollte mans hinzufügen? Habs in der ProjectService klasse jetzt noch geaddet aber ansonsten finde ich glaub ich auch nix mehr wos passen würde, aber ich kann mich auch täuschen

ja ich denke des passt jz schon so aber wir brauchen noch diese retry mechanismus (vllt auch ein extra ticket welches wir dann später machen wenn alles an code fertig ist)^^

2024-04-22 11:15 UTC, ris5266 commented
> > wo meintest du noch sollte mans hinzufügen? Habs in der ProjectService klasse jetzt noch geaddet aber ansonsten finde ich glaub ich auch nix mehr wos passen würde, aber ich kann mich auch täuschen
> 
> ja ich denke des passt jz schon so aber wir brauchen noch diesen retry mechanismus (vllt auch ein extra ticket welches wir dann später machen wenn alles an code fertig ist)^^

dann lass dazu ein neues ticket machen und das hier vllt aber dann schon mal mergen

2024-04-22 14:03 UTC, Stefan7400 requested changes

2024-04-22 14:03 UTC, Stefan7400 commented on src/main/kotlin/de/amplimind/codingchallenge/dto/request/ChangeProjectActiveStatusRequestDTO.kt
> +    val version: Long
Ein DTO braucht keine version nur Entities (also klassen welche mit `@Entity` annotiert sind

2024-04-22 14:03 UTC, Stefan7400 commented on src/main/kotlin/de/amplimind/codingchallenge/dto/request/ChangeProjectTitleRequestDTO.kt
> +    val version: Long
Ein DTO braucht keine version nur Entities (also klassen welche mit `@Entity` annotiert sind

2024-04-22 14:03 UTC, Stefan7400 commented on src/main/kotlin/de/amplimind/codingchallenge/service/ProjectService.kt
> +        if (storedProject.version != changeProjectActiveStatusRequestDTO.version) {
das if und das throw kann weg eine OptimisticLockingFailureException wird automatisch geworfen wenn repository.save aufgerufen wird^^

2024-04-22 14:03 UTC, Stefan7400 commented on src/main/kotlin/de/amplimind/codingchallenge/service/ProjectService.kt
> +        if (storedProject.version != changeProjectTitleRequestDTO.version) {
das if und das throw kann weg eine OptimisticLockingFailureException wird automatisch geworfen wenn repository.save aufgerufen wird^^

2024-04-22 14:03 UTC, Stefan7400 commented on src/main/kotlin/de/amplimind/codingchallenge/service/UserService.kt
> +            throw IllegalStateException("The user was updated by another transaction")
Des try catch kann fürs erste mal weg, um des kümmern wir uns wenn wir dieses retry von spring boot verwenden (aber dann halt in nen anderen ticket)^^

2024-04-22 14:03 UTC, Stefan7400 commented on src/main/kotlin/de/amplimind/codingchallenge/service/UserService.kt
> +        } catch (ex: OptimisticLockingFailureException) {
Des try catch einfach weg lassen

2024-04-22 14:03 UTC, Stefan7400 commented
@ris5266 Kannst du auch gleich das nächste Ticket erstellen (Add Retry-Mechanism)

2024-04-22 14:13 UTC, ris5266 commented
@Stefan7400 in der SubmissionService Klasse bleibt aber der try and catch oder wie?

2024-04-22 14:15 UTC, Stefan7400 commented
> @Stefan7400 in der SubmissionService Klasse bleibt aber der try and catch oder wie?

Ne der kann auch raus alle catches vom OptimisticLockException können weg^^

2024-04-22 14:23 UTC, merged