Test for AccountController …
amplimindcc/backend pull request #96
Opened 2024-04-29 06:33 UTC by VincentFlemmig

added tests for AccountControler; added check if user exists, before sending mail; changed error code for invalidToken from 400 to 422 (422 was set in Controller 400 in GlobalExceptionHandler)

2024-04-29 09:09 UTC, SrNski requested changes

2024-04-29 09:09 UTC, SrNski commented on src/test/kotlin/de/amplimind/codingchallenge/controller/AccountControllerTest.kt
> +        this.mackMvc.post("/v1/account/request-password-change/$email_to_reset_password"){
Kannst du den mail call mocken? Sonst wenn sich wer nen mail admin@web.de erstellt kriegt der unsere Test mails

2024-04-29 10:08 UTC, Stefan7400 approved these changes

2024-05-04 11:14 UTC, Stefan7400 approved these changes

2024-05-04 11:15 UTC, merged